[tool.poetry]
name = "sudo-bot"
version = "0.1.2"
description = "A simple bot for discord."
authors = ["matthew956"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
